<!-- /databases/Ukraine/VitalRecInventory.inc -->

<P>There are currently more than 
<!-- *** -->
26,000 records from 24 towns in this database.
</P>

<P>The following table contains the inventory of records currently 
included in this database.&nbsp;  The first column, "Town", contains 
the town's Czarist Russian-language name (circa 1900), followed by the 
modern Ukrainian-language name.&nbsp;  
The town's Russian Cyrillic and Yiddish names are also included.&nbsp; 
If you move your mouse over the town name, you will see additional 
information about this town, and a link to this town's Locality page 
in the <A HREF="/Communities">JewishGen Communities Database</A>.
</P>

<P>The last column, "Source" contains the abbreviated name of the source(s)
of this town's data; the archives which hold the original data.&nbsp; 
Details about these abbreviations can be found under 
"<A HREF="#Sources">Source Archives</A>" below.
</P>


<TABLE CLASS="jgtable" border=1 cellpadding=2 cellspacing=0 ID="TableInv">

<THEAD>
<TR>
 <TH>Town<BR>
     <SPAN class="smalltext">(Russian / Ukrainian names)</SPAN></TH>
 <TH>Gubernia<BR>Uyezd</TH>
 <TH>Record<BR>Type</TH>
 <TH>Years</TH>
 <TH># of<BR>Records</TH>
 <TH>Source</TH>
 </TR>
</THEAD>

<TBODY>
<TR valign='top'>
 <td CLASS="shtet" USBGN="-1035624"><B>Belaya Tserkov</B> / Bila Tserkva<BR>
     Белая Церковь / שוואַרץ־טומאה </td>
 <td align='center'>Kiev<BR><SPAN class="smalltext">Vasilkov</SPAN></td>
 <td>Births</td>
 <td>1850</td>
 <td align='right'>138</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1036778" rowspan=3><B>Byshev</B> / Byshiv <BR>
     Бышев / בישעוו</td>
 <td align='center' rowspan=3>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Births</td>
 <td>1854-56</td>
 <td align='right'>114</td>
 <td>FHL, TsDIAU</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1854-55</td>
 <td align='right'>12</td>
 <td>FHL, TsDIAU</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1854-55</td>
 <td align='right'>52</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1037057" rowspan=2><B>Chernigov</B> / Chernihiv <BR>
     Чернигов / טשערניִעוו </td>
 <td align='center' rowspan=2>Chernigov<BR><SPAN class="smalltext">Chernigov</SPAN></td>
 <td>Marriages</td>
 <td>1889-91, 1904, 1907, 1910-15, 1918</td>
 <td align='right'>653</td>
 <td>FHL, SACU</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1881, 1906-08, 1913-15, 1917-18</td>
 <td align='right'>1,833</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1039476"><B>Gorodniya</B> / Horodniya <BR>
     Городня / האָראָדניע </td>
 <td align='center'>Chernigov<BR><SPAN class="smalltext">Horodnia</SPAN></td>
 <td>Marriages</td>
 <td>1908, 1912, 1914</td>
 <td align='right'>112</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1039545"><B>Gostomel</B> / Hostomel’ <BR>
     Гостомель / אַסטאָמליע </td>
 <td align='center'>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Births</td>
 <td>1855</td>
 <td align='right'>14</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1040059" rowspan=2><B>Ignatovka</B> / Hnativka <BR>
     Игнатовка / אנטבקה </td>
 <td align='center' rowspan=2>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Births</td>
 <td>1854-55</td>
 <td align='right'>85</td>
 <td>FHL, TsDIAU</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1854</td>
 <td align='right'>36</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1044367"><B>Kiev</B> / Kyyiv <BR>
     Киев / קיִעװ </td>
 <td align='center'>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Births</td>
 <td>1850</td>
 <td align='right'>56</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1042673"><B>Konotop</B> <BR>
     Конотоп / קאָנאָטאָפּ </td>
 <td align='center'>Chernigov<BR><SPAN class="smalltext">Konotop</SPAN></td>
 <td>Marriages</td>
 <td>1907</td>
 <td align='right'>120</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1042893"><B>Korop</B> <BR>
     Короп </td>
 <td align='center'>Chernigov<BR><SPAN class="smalltext">Krolovets</SPAN></td>
 <td>Marriages</td>
 <td>1904, 1906-07</td>
 <td align='right'>67</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1043526" rowspan=4><B>Krasnoye</B> / Krasne <BR>
     Красное / קראָסנע</td>
 <td align='center' rowspan=4>Podolia<BR><SPAN class="smalltext">Yampol</SPAN></td>
 <td>Births</td>
 <td>1838-39, 1841-42, 1846, 1848-49, 1851</td>
 <td align='right'>819</td>
 <td>KhRSA</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1839, 1841-42, 1844, 1846, 1848-49, 1851</td>
 <td align='right'>80</td>
 <td>KhRSA</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1841</td>
 <td align='right'>2</td>
 <td>KhRSA</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1839, 1841-42, 1844, 1848-52</td>
 <td align='right'>530</td>
 <td>KhRSA</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1043812"><B>Krolovets</B> <BR>
     Кролевец / קראָלאָוועץ</td>
 <td align='center'>Chernigov<BR><SPAN class="smalltext">Krolovets</SPAN></td>
 <td>Marriages</td>
 <td>1904</td>
 <td align='right'>26</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1045481" rowspan=3><B>Makarov</B> / Makariv <BR>
     Макаров / מעקאַרעוו</td>
 <td align='center' rowspan=3>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Marriages</td>
 <td>1854</td>
 <td align='right'>31</td>
 <td>FHL, TsDIAU</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1854</td>
 <td align='right'>16</td>
 <td>FHL, TsDIAU</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1854</td>
 <td align='right'>89</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1046905" rowspan=4><B>Mogilev-Podolskiy</B> / 
     <NOBR>Mohyliv-Podil's'kyy</NOBR><BR>
     Могилёв-Подольский / מאָהילעװ </td>
 <td align='center' rowspan=4>Podolia<BR><SPAN class="smalltext">Mogilev</SPAN></td>
 <td>Births</td>
 <td>1844</td>
 <td align='right'>286</td>
 <td>CAHJP</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1844</td>
 <td align='right'>70</td>
 <td>CAHJP</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1844</td>
 <td align='right'>29</td>
 <td>CAHJP</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1844</td>
 <td align='right'>160</td>
 <td>CAHJP</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1047094" rowspan=3><B>Moshny</B> <BR>
     Мошни / מאשנע </td>
 <td align='center' rowspan=3>Kiev<BR><SPAN class="smalltext">Cherkassy</SPAN></td>
 <td>Births</td>
 <td>1845-48, 1850-52, 1859, 1861-62, 1868, 1886, 1889-90, 1893, 1915</td>
 <td align='right'>615</td>
 <td>FHL, SACO</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1846, 1851, 1853, 1855, 1858-59, 1861-62, 1866, 1888, 1895</td>
 <td align='right'>91</td>
 <td>FHL, SACO</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1846-47, 1859, 1861</td>
 <td align='right'>7</td>
 <td>FHL, SACO</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1047154" rowspan=2><B>Motyzhin</B> / Motyzhyn <BR>
     Мотыжин </td>
 <td align='center' rowspan=2>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Marriages</td>
 <td>1854</td>
 <td align='right'>6</td>
 <td>FHL, TsDIAU</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1846-48, 1850-51, 1853, 1873, 1893, 1917-18</td>
 <td align='right'>194</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1047887" rowspan=2><B>Nezhin</B> / Nizhyn <BR>
     Нежен / ניעזשין </td>
 <td align='center' rowspan=2>Chernigov<BR><SPAN class="smalltext">Niezhin</SPAN></td>
 <td>Births</td>
 <td>1881-83</td>
 <td align='right'>973</td>
 <td>FHL, SACU</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1904, 1907, 1909-10, 1914, 1916, 1918</td>
 <td align='right'>303</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1047257" rowspan=4><B>Nikolayev</B> / Mykolayiv <BR>
     Николаев / מיקאָלײַעווע </td>
 <td align='center' rowspan=4>Kherson<BR><SPAN class="smalltext">Nikolayev</SPAN></td>
 <td>Births</td>
 <td>1878, 1889-95</td>
 <td align='right'>4,311</td>
 <td>FHL, NKKR</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1877</td>
 <td align='right'>33</td>
 <td>FHL, NKKR</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1867</td>
 <td align='right'>11</td>
 <td>FHL, NKKR</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1876, 1877</td>
 <td align='right'>373</td>
 <td>FHL, NKKR</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1051731" rowspan=4><B>Priluki</B> / Pryluky <BR>
     Прилуки / פּרילוקי </td>
 <td align='center' rowspan=4>Poltava<BR><SPAN class="smalltext">Priluki</SPAN></td>
 <td>Births</td>
 <td>1855-59, 1861, 1863-68, 1871-77</td>
 <td align='right'>2,848</td>
 <td>FHL, SACU</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1855, 1858-59, 1860-61, 1863, 1865-66, 1868-70, 1873-75, 1877</td>
 <td align='right'>547</td>
 <td>FHL, SACU</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1855, 1873, 1876-77</td>
 <td align='right'>19</td>
 <td>FHL, SACU</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1856-59, 1860, 1862-63, 1865-66, 1868-71, 1873-75, 1877, 1899</td>
 <td align='right'>1,502</td>
 <td>FHL, SACU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1052850" rowspan=2><B>Rzhishchev</B> / Rzhyshchiv <BR>
     Ржищев / רעזשישטשעוו </td>
 <td align='center' rowspan=2>Kiev<BR><SPAN class="smalltext">Kiev</SPAN></td>
 <td>Divorces</td>
 <td>1854</td>
 <td align='right'>9</td>
 <td>FHL</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1852-54</td>
 <td align='right'>300</td>
 <td>FHL, TsDIAU</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1053923" rowspan=3><B>Shpikov</B> / Shpykiv <BR>
     Шпиков / שפּיקעוו </td>
 <td align='center' rowspan=3>Podolia<BR><SPAN class="smalltext">Bratslav</SPAN></td>
 <td>Births</td>
 <td>1839, 1840-42, 1848, 1850-51</td>
 <td align='right'>214</td>
 <td>CAHJP, KhRSA</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1839-1842, 1848, 1850-51</td>
 <td align='right'>31</td>
 <td>CAHJP, KhRSA</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1839-40, 1842, 1850-51</td>
 <td align='right'>104</td>
 <td>CAHJP, KhRSA</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1054390" rowspan=4><B>Smiela</B> / Smila <BR>
     Смела / סמילע </td>
 <td align='center' rowspan=4>Kiev<BR><SPAN class="smalltext">Cherkassy</SPAN></td>
 <td>Births</td>
 <td>1840-44, 1846, 1892</td>
 <td align='right'>655</td>
 <td>FHL, SACO</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1841-42, 1846</td>
 <td align='right'>92</td>
 <td>FHL, SACO</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1841, 1846</td>
 <td align='right'>29</td>
 <td>FHL, SACO</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1841, 1843, 1846</td>
 <td align='right'>233</td>
 <td>FHL, SACO</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1059068"><B>Vyazovka</B> / V'yazivka <BR>
     Вязовка / וויאַזאָווקע </td>
 <td align='center'>Volhynia<BR><SPAN class="smalltext">Ovruch</SPAN></td>
 <td>Births</td>
 <td>1892</td>
 <td align='right'>20</td>
 <td>FHL, SACO</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1040503" rowspan=2><B>Zaslav</B> / Izyaslav <BR>
     Заслав / Заславль / זאַסלעוו </td>
 <td align='center' rowspan=2>Volhynia<BR><SPAN class="smalltext">Zaslav</SPAN></td>
 <td>Births</td>
 <td>1845-51</td>
 <td align='right'>1,106</td>
 <td>ZaSAVO</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1848-51, 1853-65, 1867-81</td>
 <td align='right'>6,353</td>
 <td>ZaSAVO</td>
</TR>


<TR valign='top'>
 <td CLASS="shtet" USBGN="-1060918" rowspan=4><B>Zinkov</B> / Zinkiv <BR>
     Зиньков / זינקעוו </td>
 <td align='center' rowspan=4>Podolia<BR><SPAN class="smalltext">Letichev</SPAN></td>
 <td>Births</td>
 <td>1839, 1849-50</td>
 <td align='right'>341</td>
 <td>ZiRK</td>
 </tr>

<TR valign='top'>
 <td>Marriages</td>
 <td>1839, 1849-50</td>
 <td align='right'>71</td>
 <td>ZiRK</td>
 </tr>

<TR valign='top'>
 <td>Divorces</td>
 <td>1849</td>
 <td align='right'>4</td>
 <td>ZiRK</td>
 </tr>

<TR valign='top'>
 <td>Deaths</td>
 <td>1849-50</td>
 <td align='right'>160</td>
 <td>ZiRK</td>
</TR>
</TBODY>

<TFOOT>
<TR valign='top'>
 <td colspan="4">TOTAL</td>
 <td align='right'>26,985</td>
 <td>&nbsp;</td>
 </tr>
</TFOOT>
</TABLE>


<SCRIPT src="/Ajax/popUpHypertext.js" type="text/javascript"></SCRIPT>